import { generateApiKey, verifyApiKey, maskApiKey, generateApiKeyId } from '@/lib/api-key-auth';

// Mock the ApiKeyRepository to avoid DB dependency
jest.mock('@/repositories/api-key.repo', () => ({
  ApiKeyRepository: {
    findByPrefix: jest.fn(),
  },
}));

import { ApiKeyRepository } from '@/repositories/api-key.repo';

describe('api-key-auth', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('generateApiKey', () => {
    it('should generate a key with mi- prefix', () => {
      const { fullKey, keyPrefix, keyHash } = generateApiKey();
      expect(fullKey).toMatch(/^mi-/);
      expect(keyPrefix).toMatch(/^mi-/);
      expect(keyHash).toBeDefined();
      expect(keyHash.length).toBeGreaterThan(0);
    });

    it('should generate a key of expected total length (prefix + 42 chars)', () => {
      const { fullKey } = generateApiKey();
      // mi- prefix (3) + 42 random chars = 45 total
      expect(fullKey.length).toBe(45);
    });

    it('should generate unique keys on consecutive calls', () => {
      const key1 = generateApiKey();
      const key2 = generateApiKey();
      expect(key1.fullKey).not.toBe(key2.fullKey);
      expect(key1.keyHash).not.toBe(key2.keyHash);
    });

    it('should generate a keyPrefix that is the first 20 chars of fullKey', () => {
      const { fullKey, keyPrefix } = generateApiKey();
      expect(keyPrefix).toBe(fullKey.substring(0, 20));
    });
  });

  describe('verifyApiKey', () => {
    it('should verify a valid key that was generated by generateApiKey', async () => {
      const { fullKey, keyHash } = generateApiKey();
      // Mock findByPrefix to return a record with the correct key_hash
      (ApiKeyRepository.findByPrefix as jest.Mock).mockResolvedValue({
        id: 'ak_test',
        user_id: 'user-1',
        key_prefix: fullKey.slice(0, 20),
        key_hash: keyHash,
      });

      const result = await verifyApiKey(`Bearer ${fullKey}`);
      expect(result).not.toBeNull();
      expect(result).toHaveProperty('apiKeyId', 'ak_test');
      expect(result).toHaveProperty('userId', 'user-1');
    });

    it('should reject a wrong key', async () => {
      const { fullKey } = generateApiKey();
      // Mock findByPrefix to return a record with a DIFFERENT hash
      const { keyHash: wrongHash } = generateApiKey();
      (ApiKeyRepository.findByPrefix as jest.Mock).mockResolvedValue({
        id: 'ak_test',
        user_id: 'user-1',
        key_prefix: fullKey.slice(0, 20),
        key_hash: wrongHash,
      });

      const result = await verifyApiKey(`Bearer ${fullKey}`);
      expect(result).toBeNull();
    });

    it('should reject empty Bearer token', async () => {
      const result = await verifyApiKey('');
      expect(result).toBeNull();
    });

    it('should reject token without Bearer prefix', async () => {
      const { fullKey } = generateApiKey();
      const result = await verifyApiKey(fullKey);
      expect(result).toBeNull();
    });

    it('should reject token without mi- prefix', async () => {
      const result = await verifyApiKey('Bearer xx-invalidkey');
      expect(result).toBeNull();
    });
  });

  describe('maskApiKey', () => {
    it('should return first 20 chars with ellipsis', () => {
      const { fullKey } = generateApiKey();
      const masked = maskApiKey(fullKey);
      expect(masked).toContain('...');
      expect(masked.startsWith('mi-')).toBe(true);
    });

    it('should handle short keys by returning them as-is', () => {
      const masked = maskApiKey('short');
      expect(masked).toBe('short');
    });
  });

  describe('generateApiKeyId', () => {
    it('should generate an ID with ak_ prefix', () => {
      const id = generateApiKeyId();
      expect(id).toMatch(/^ak_/);
      expect(id.length).toBe(35); // ak_ + 32 hex chars
    });

    it('should generate unique IDs', () => {
      const id1 = generateApiKeyId();
      const id2 = generateApiKeyId();
      expect(id1).not.toBe(id2);
    });
  });
});
